### ISSUE TITLE
Faith creation issues (mostly regarding tenets)

### ISSUE THREAD

**Issue by JukeJukestar** [CK3RealmsinExile/RealmsInExile#447]
There are some oversights regarding faith creation, certain tenets should have more restrictions for selecting them.

## Consolamentum/ Endura:
<details> <summary>The Endura Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179553631-b04d0905-2a4d-4849-aaba-cb16ac1b2488.png)

</details>
Already has its own issue #369. Old characters commit suicide in their sixties even if they have high tier numenorean blood. Has been renamed to "Endura", since this is hard to test I do not know wether this issue has been fixed since it was first reported.
Should also be restricted so it cannot be selected by Elven faiths because it makes no sense.

## Druedain Isolation
<details> <summary>The Druedain Isolation Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179553575-44e60a52-d62b-4064-8e98-10b56960cdb3.png)

</details>
Should only be selectable for druedain religions.

## Legacy of the Great Revolt
<details> <summary>The Legacy of the Great Revolt Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179553356-20a71fd4-8401-43d7-a39c-dd9bc0304cfb.png)

</details>
Should only be selectable for Near Haradric faiths with the "Echoes of the Ainur" doctrine.

## Bellakari Syncretism
<details> <summary>The Bellakari Syncretism Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179553659-a32dd0c8-0284-4f32-875e-c4d6b2404a60.png)

</details>
Should not be selectable for faiths with the "dominion of the dark" doctrine.

## Unquiet Waters
<details> <summary>The Unquiet Waters Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179553504-8ae97cf8-ad34-48fe-9c07-34671911ab3e.png)

</details>
Should only be selectable for Gwaithuirim religions.

## The Dark Worship
<details> <summary>The The Dark Worship (sic) Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179552617-02e24f9e-d395-418b-854d-2868cc72316e.png)

</details>
Should only be avaiable to Forces of Evil faiths or men of darkness faiths with "Dominion of the Dark".
Unsure if this one is WIP, as no faith currently uses it and it has partially broken localization.

## Bhakti
<details> <summary>The Bhakti Tenet</summary> 

![image](https://user-images.githubusercontent.com/76008882/179552214-e77518f9-e9da-4f2a-90b3-c5e50046a74d.png)

</details>
This Tenet is nonfunctional and doesnt do anything. Should also be renamed and overhauled, or removed.

**Comment by jj248** [comment]
Consolamentum: Now unavailable for elven religion.
Druedain Isolation: Now unavailable to pick - if Druedain faiths move away from this historic tenet, it is lost.
Legacy of the Great Revolt: Now unavailable to pick - if Chelkar's faith moves away from this historic tenet, it is lost.
Bellakari Syncretism: Now only available to non-Forces of Evil members of the Bellakar and Far Harad Religions.
Unquiet Waters: Now only available to non-Eruhini Gwathuirim Religions.
Bhakti: Removed for now.

Dark Worship and Dragon Boshfai - I agree.  These are unfinished and I think started by Remerod for Gundabad.  @VectorMaximus - thoughts?  Shall we just replace it for now with a different tenet and comment these out?

**Comment by VectorMaximus** [comment]
Agreed. For now let's replace Dark Worship and Dragon Boshfai with a vanilla tenet.

**Comment by jj248** [comment]
That should finish it off.  Over to testing it goes.

**Comment by JukeJukestar** [comment]
- Adorcism is disallowed for good aligned faiths (I think? Its a bit hard to tell, men of darkness can select it but the druedain cant reform with it)
- Druedain Isolation is disallowed for all faiths when trying to reform/ create a new faith, including druedain
- Legacy of the Great Revolt is disallowed when trying to create a new faith from Nadi-Manye

**Comment by jj248** [comment]
Thanks Juke.

- Adorcism is only available to non-Eruhini, non-Forces of Evil family religions.  So the following faiths have this who wouldn't normally be able to select them and won't be able to retain them on reform as a result: Fiskurkyn, Honnin, Druedain.  Solution is to either widen availability or to change tenets for those faiths.  One for @VectorMaximus.
- Other two should be fixed.

**Comment by VectorMaximus** [comment]
So, my thought is that for the 'Free Peoples', who are supposed to be more spiritually enlightened, the 'Seek the aid of the spirits' doesn't feel very proper. Specific causes (such as the Druedain/Honnin) seemed more acceptable to me, hence they broke the rule. I suppose I'd prefer widening the availability than changing the tenets.

**Comment by jj248** [comment]
Pushing back to testing.

**Comment by JukeJukestar** [comment]
- Druedain can now reform as intended
- Adorcism still not allowed for other free peoples. I can see vecs reasoning but I think we should allow players to choose it, since there are also some free peoples faiths who arent "spiritually enlightened" (Freastroa, blue sect, widumannas?

**Comment by JukeJukestar** [comment]
Workin as intended. Closing
